name: Android APK Build

on:
  push:
    branches:
      - main
      - master
  pull_request:


jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      
      
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      
      
      
      
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      
      
      
      
      - name: Clean Build Directory
        run: |
          rm -rf app/build
      
      
      
      
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      
      
      
      
      - name: Setup Keystore
        if: contains(github.event.head_commit.message, 'release')
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
      
      
      
      
      - name: Verify Keystore File
        if: contains(github.event.head_commit.message, 'release')
        run: |
          if [ -s "keystore.jks" ]; then
            echo "Keystore file exists and is non-empty."
            ls -lh keystore.jks
          else
            echo "Keystore file is missing or empty!" && exit 1
          fi
      
      
      
      
      - name: Verify Keystore Integrity
        if: contains(github.event.head_commit.message, 'release')
        run: |
          echo "Listing keystore contents:"
          keytool -list -keystore keystore.jks -storepass "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" || { echo "Keystore verification failed!"; exit 1; }
      
      
      
      
      - name: Verify matching keystore and key passwords
        if: contains(github.event.head_commit.message, 'release')
        run: |
          if [ "$ANDROID_KEYSTORE_PASSWORD" = "$ANDROID_KEY_PASSWORD" ]; then
            echo "Keystore password and key password match."
          else
            echo "Error: Keystore password and key password do not match!" && exit 1
          fi
      
      
      
      
      - name: Build APK
        id: build_apk
        continue-on-error: true
        run: |
          ./gradlew clean
          if [[ "${{ github.event.head_commit.message }}" == *release* ]]; then
            ./gradlew assembleRelease
          elif [[ "${{ github.event.head_commit.message }}" == *debug* ]]; then
            ./gradlew assembleDebug
          else
            echo "No matching keyword in commit message (neither release nor debug), skipping build"
            exit 0
          fi
      
      
      
      
      - name: List APK Outputs
        run: |
          echo "APK files in app/build/outputs/apk:"
          find app/build/outputs/apk -type f -name "*.apk"
      
      
      
      
      - name: Debug Build Failure (Stacktrace, Info, Scan)
        if: failure()
        run: |
          echo "Build failed, re-running with debug options..."
          if [[ "${{ github.event.head_commit.message }}" == *release* ]]; then
            ./gradlew assembleRelease --stacktrace --info --scan
          elif [[ "${{ github.event.head_commit.message }}" == *debug* ]]; then
            ./gradlew assembleDebug --stacktrace --info --scan
          fi
          exit 1
      
      
      
      
      - name: Upload APK Artifact (Release)
        if: contains(github.event.head_commit.message, 'release')
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
      
      
      
      
      - name: Upload APK Artifact (Debug)
        if: contains(github.event.head_commit.message, 'debug')
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk