name: Android APK Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Grant execute permission to Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # If the commit message contains "release", set up the keystore for signing.
      - name: Setup Keystore
        if: contains(github.event.head_commit.message, 'release')
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > keystore.jks

      # Build APK: if commit message contains "release", build the release APK; otherwise, build the debug APK.
      - name: Build APK
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *release* ]]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi

      # Upload the built APK as an artifact.
      - name: Upload APK Artifact (Release)
        if: contains(github.event.head_commit.message, 'release')
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload APK Artifact (Debug)
        if: ${{ !contains(github.event.head_commit.message, 'release') }}
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk