name: Fix Gradle Wrapper

on:
  push:
    branches:
      - main  # Change if using another branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  fix-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download & Extract Gradle Wrapper JAR
        run: |
          GRADLE_VERSION="8.4"
          JAR_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"

          # Download Gradle distribution
          wget -q "$JAR_URL" -O gradle.zip

          # Extract only the gradle-wrapper.jar
          unzip -j gradle.zip "**/gradle-wrapper.jar" -d gradle/wrapper/

          # Cleanup
          rm gradle.zip

      - name: Verify Checksum
        run: |
          CHECKSUM="f2b9ed0faf8472cbe469255ae6c86eddb77076c75191741b4a462f33128dd419"
          echo "$CHECKSUM  gradle/wrapper/gradle-wrapper.jar" | sha256sum --check --status && echo "Checksum verified!" || (echo "Checksum mismatch!" && exit 1)

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add gradle/wrapper/gradle-wrapper.jar
          git commit -m "Fix: Replace corrupted Gradle Wrapper with verified version" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # Avoids failure if no changes

      - name: Trigger Build Workflow
        run: gh workflow run build.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
