name: Fetch Gradle Wrapper

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Download Gradle Distribution & Checksum
        run: |
          GRADLE_VERSION="8.4"
          JAR_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
          CHECKSUM_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip.sha256"

          # Download files
          wget -q "$JAR_URL" -O gradle.zip
          wget -q "$CHECKSUM_URL" -O gradle.zip.sha256

      - name: Verify ZIP Checksum
        run: |
          EXPECTED_CHECKSUM=$(cat gradle.zip.sha256 | tr -d ' \n')
          ACTUAL_CHECKSUM=$(sha256sum gradle.zip | awk '{ print $1 }')

          echo "Expected: $EXPECTED_CHECKSUM"
          echo "Actual:   $ACTUAL_CHECKSUM"

          if [[ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]]; then
            echo "ZIP Checksum mismatch!"
            exit 1
          fi

      - name: Extract Gradle Wrapper JAR
        run: |
          mkdir -p gradle/wrapper
          unzip -j gradle.zip "gradle-8.4/lib/plugins/gradle-wrapper-8.4.jar" -d gradle/wrapper/
          mv gradle/wrapper/gradle-wrapper-8.4.jar gradle/wrapper/gradle-wrapper.jar

      - name: Upload Wrapper JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-wrapper
          path: gradle/wrapper/gradle-wrapper.jar
          retention-days: 7  # Keep for 7 days
